prefix: data/
suffix: .fq.gz
forward_suffix: _1
reverse_suffix: _2
reference_genome: GCF_021228175.1/GCF_021228175.1_ASM2122817v1_genomic.fna
reference_annotation: GCF_021228175.1/genomic.gff
streaming_chunk_size: 1000000
bc_cutoff: 14000
feature_tag: gene
gene_id_attribute: Name
samples:
  PSeqA:
    prefix: PseqA/PseqA_EKDN240010018-1A_
    lanes:
      L1: 223YJCLT4_L1
      L4: H77W3DSXC_L4
  PseqB:
    prefix: PseqB/PseqB_EKDN240010019-1A_
    lanes:
      L1: 223WMMLT4_L1
      L4: H77W3DSXC_L4
  PSeqC:
    prefix: PseqC/PseqC_EKDN240010020-1A_
    lanes:
      L1: 223YJCLT4_L1
      L2: H77W3DSXC_L2
  PSeqD:
    prefix: PseqD/PseqD_EKDN240010021-1A_
    lanes:
      L1: 223YJCLT4_L1
      L4: H77W3DSXC_L4
