prefix: data/
suffix: .fastq
forward_suffix: _1
reverse_suffix: _2
reference_genome: GCF_000005845.2/GCF_000005845.2_ASM584v2_genomic.fna
reference_annotation: GCF_000005845.2/genomic.gff
streaming_chunk_size: 200000
bc_cutoff: 14000
feature_tag: gene
gene_id_attribute: Name
samples:
  Rep1:
    prefix: GSE260457/SRR25445880
    lanes:
      L1: 
  Rep2:
    prefix: GSE260457/SRR25445879
    lanes:
      L1: 