prefix: data/

samples:
  PETRI-seq-2.01:
    bc_cutoff: 10000
    prefix: GSE141018/
    lanes:
      L1: SRR11584024
      L2: SRR11584025
    forward_suffix: _1
    reverse_suffix: _2
    suffix: .fastq
  

reference_genome: U000096_JE2.fa 

reference_annotation: U000096_JE2_rRNA.gff 

feature_tag: Coding_or_RNA

gene_id_attribute: name

streaming_chunk_size: 1e6
