name: petriseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - cutadapt
  - umi_tools
  - subread
  - bwa
  - pandas
  - numpy
  - matplotlib
  - samtools
  - ipython
  - pear
  - seqkit
  - snakemake
  - snakefmt
  - radian
  - r-languageserver
  - bioconductor-biostrings
  - bioconductor-genomicalignments
  - bioconductor-rtracklayer
  - r-dplyr
  - r-ggplot2
  - bioconductor-rsamtools
  - graphviz
  - r-rcpp
  - r-shiny
  - bioconductor-shortread
  - r-data.table
  - diamond
  - megan
prefix: /home/japet/miniforge3/envs/petriseq
