name: petriseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - cutadapt
  - umi_tools
  - subread
  - bwa
  - pandas
  - samtools
  - ipython
  - snakemake
  - snakefmt
  - radian
  - r-languageserver
  - bioconductor-biostrings
  - r-dplyr
  - r-ggplot2
  - r-rcpp
  - r-shiny
  - r-dt
  - bioconductor-shortread
  - r-data.table
  - r-chunked
  - r-dbplyr
  - sra-tools
  - r-rsqlite
  - r-yaml
  - r-shinythemes
  - r-shinybs
prefix: /home/japet/miniforge3/envs/petriseq
