name: petriseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - apptainer
  - fuse2fs
  - fastqc
  - cutadapt
  - umi_tools
  - subread
  - bwa
  - pandas
  - samtools
  - ipython
  - snakemake
  - snakefmt
  - radian
  - r-languageserver
  - bioconductor-biostrings
  - r-dplyr
  - r-ggplot2
  - r-rcpp
  - r-shiny
  - r-dt
  - bioconductor-shortread
  - r-chunked
  - r-dbplyr
  - sra-tools
  - r-rsqlite
  - r-readr
  - r-yaml
  - r-shinythemes
  - r-shinybs
  