prefix: resources/

samples:
  random20000:
    bc_cutoff: 3000
    prefix: random20000/random20000_S1_
    lanes:
      L1: L001
    forward_suffix: _R1
    reverse_suffix: _R2
    suffix: _001.fastq.gz

reference_genome: U00096_JE2.fa

reference_annotation: U00096_JE2_rRNA.gff

feature_tag: Coding_or_RNA

gene_id_attribute: name

streaming_chunk_size: 4000
