prefix: resources/
suffix: .fastq
forward_suffix: _1
reverse_suffix: _2
reference_genome: GCF_000005845.2/GCF_000005845.2_ASM584v2_genomic.fna
reference_annotation: GCF_000005845.2/genomic.gtf
feature_tag: CDS  
gene_id_attribute: gene_id
samples:
  EC_3h_deep:
    prefix: GSE260457/
    bc_cutoff: 60000
    lanes:
      L1: SRR28148450
